<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260316232748 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE webauthn_credential (id VARCHAR(255) NOT NULL, credential_data TEXT NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_850123F9A76ED395 ON webauthn_credential (user_id)');
        $this->addSql('ALTER TABLE webauthn_credential ADD CONSTRAINT FK_850123F9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE admin ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE admin ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uniq_admin_username RENAME TO UNIQ_880E0D76F85E0677');
        $this->addSql('ALTER TABLE events ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE events ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT fk_reservations_event');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT fk_reservations_user');
        $this->addSql('ALTER TABLE reservations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reservations ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN reservations.created_at IS \'\'');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA23971F7E88B FOREIGN KEY (event_id) REFERENCES events (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT FK_4DA239A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_reservations_event RENAME TO IDX_4DA23971F7E88B');
        $this->addSql('ALTER INDEX idx_reservations_user RENAME TO IDX_4DA239A76ED395');
        $this->addSql('ALTER TABLE "user" ADD user_handle UUID DEFAULT NULL');
        // generate uuids for existing rows, utilizing postgres internal function if needed OR a placeholder
        $this->addSql('UPDATE "user" SET user_handle = gen_random_uuid() WHERE user_handle IS NULL');
        $this->addSql('ALTER TABLE "user" ALTER COLUMN user_handle SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER roles DROP DEFAULT');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F4D23BE4 ON "user" (user_handle)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE webauthn_credential DROP CONSTRAINT FK_850123F9A76ED395');
        $this->addSql('DROP TABLE webauthn_credential');
        $this->addSql('ALTER TABLE admin ALTER id SET DEFAULT nextval(\'admin_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE admin ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_880e0d76f85e0677 RENAME TO uniq_admin_username');
        $this->addSql('ALTER TABLE events ALTER id SET DEFAULT nextval(\'events_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE events ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA23971F7E88B');
        $this->addSql('ALTER TABLE reservations DROP CONSTRAINT FK_4DA239A76ED395');
        $this->addSql('ALTER TABLE reservations ALTER id SET DEFAULT nextval(\'reservations_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE reservations ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN reservations.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT fk_reservations_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reservations ADD CONSTRAINT fk_reservations_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_4da23971f7e88b RENAME TO idx_reservations_event');
        $this->addSql('ALTER INDEX idx_4da239a76ed395 RENAME TO idx_reservations_user');
        $this->addSql('DROP INDEX UNIQ_8D93D649F4D23BE4');
        $this->addSql('ALTER TABLE "user" DROP user_handle');
        $this->addSql('ALTER TABLE "user" ALTER id SET DEFAULT nextval(\'user_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE "user" ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE "user" ALTER roles SET DEFAULT \'[]\'');
    }
}